using System.Globalization;
using System.Net;
using System.Text;

namespace Silen.Services.Helpers;

/// <summary>
/// Renders the "your AI plan is ready" email WeeklyPlanGenerationService sends every
/// Sunday - the weekly counterpart of <see cref="MonthlyReviewEmailRenderer"/>. All
/// user-authored text is HTML-encoded before it reaches the markup.
/// </summary>
public static class WeeklyPlanEmailRenderer
{
    public static string BuildSubject(DateTime weekStartUtc) =>
        $"Your plan for the week of {weekStartUtc:MMM d} is ready";

    public static string BuildHtml(
        string? displayName,
        string splitName,
        bool splitKept,
        string dietPlanName,
        IReadOnlyList<string> shoppingList,
        DateTime weekStartUtc)
    {
        var name = string.IsNullOrWhiteSpace(displayName) ? "Athlete" : displayName.Trim();
        var weekLabel = weekStartUtc.ToString("MMM d", CultureInfo.InvariantCulture);
        var body = new StringBuilder();

        body.Append("<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;")
            .Append("max-width:600px;margin:0 auto;color:#1f2937;line-height:1.5;\">");
        body.Append($"<h1 style=\"font-size:22px;margin:0 0 4px;\">Your week of {Encode(weekLabel)}, planned</h1>");
        body.Append($"<p style=\"margin:0 0 20px;color:#6b7280;\">Hi {Encode(name)}, your AI coach looked at what you " +
                    "trained and ate last week and built you a fresh plan for this one.</p>");

        body.Append("<table role=\"presentation\" style=\"width:100%;border-collapse:collapse;font-size:14px;\">");
        body.Append(splitKept
            ? SummaryRow("Your split", "Kept your current split")
            : SummaryRow("New split", splitName));
        body.Append(SummaryRow("New meal plan", dietPlanName));
        body.Append("</table>");

        if (shoppingList.Count > 0)
        {
            body.Append("<h2 style=\"font-size:16px;margin:28px 0 8px;\">Your shopping list</h2>");
            body.Append("<p style=\"margin:0 0 10px;color:#6b7280;font-size:13px;\">" +
                        "Everything you need for the week's meals.</p>");
            body.Append("<ul style=\"margin:0;padding-left:20px;font-size:14px;\">");
            foreach (var ingredient in shoppingList)
            {
                body.Append($"<li style=\"margin:2px 0;\">{Encode(ingredient)}</li>");
            }

            body.Append("</ul>");
        }

        body.Append("<p style=\"margin:24px 0 0;font-size:14px;\">Open the app to see the full breakdown - " +
                    "and tap \"Keep this plan\" on either one if you want it to stick around past this week.</p>");

        body.Append("<p style=\"margin:28px 0 0;font-size:12px;color:#9ca3af;\">Generated by SilaFit. Keep training.</p>");
        body.Append("</div>");

        return body.ToString();
    }

    private static string SummaryRow(string label, string value) =>
        $"<tr><td style=\"padding:4px 0;color:#6b7280;width:40%;\">{Encode(label)}</td>" +
        $"<td style=\"padding:4px 0;text-align:right;font-weight:600;\">{Encode(value)}</td></tr>";

    private static string Encode(string value) => WebUtility.HtmlEncode(value);
}
